config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :ventes
  resources :produits
  resources :stocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "vente#index"
end

app/models/produit.rb
class Produit < ApplicationRecord
    validates :name, :quantity, :price, presence: true

    has_many :ventes, dependent: :destroy
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: %i[ show edit update destroy ]

  # GET /produits or /produits.json
  def index
    @produits = Produit.all
  end

  # GET /produits/1 or /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits or /produits.json
  def create
    @produit = Produit.new(produit_params)

    respond_to do |format|
      if @produit.save
        format.html { redirect_to @produit, notice: "Produit was successfully created." }
        format.json { render :show, status: :created, location: @produit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produits/1 or /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to @produit, notice: "Produit was successfully updated." }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1 or /produits/1.json
  def destroy
    @produit.destroy!

    respond_to do |format|
      format.html { redirect_to produits_path, status: :see_other, notice: "Produit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def produit_params
      params.expect(produit: [ :name, :quantity, :price, :image ])
    end
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/produits/_form.html.erb
<%= form_with(model: produit) do |form| %>
  <% if produit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
        <% produit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image, class:"form-control" %>
  </div>

<br/>
  <div class="form-group">
    <%= form.submit "Valider", class:"btn btn-primary form-control" %>
  </div>
<% end %>

app/views/produits/_produit.html.erb
<div id="<%= dom_id produit %>">
  <p>
    <strong>Name:</strong>
    <%= produit.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= produit.quantity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= produit.price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= produit.image %>
  </p>

</div>

app/views/produits/edit.html.erb
<% content_for :title, "Editing produit" %>

<h1>Faire une modification</h1>


<%= render "form", produit: @produit %>

<br>

<div class="d-flex justify-content-around">
  <%= link_to "Retour", produits_path, class:"btn btn-outline-primary" %>
  <%= link_to "Voir +", @produit, class:"btn btn-primary" %> 
</div>

app/views/produits/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="form-group col-4 d-flex mx-auto ">
  <%= link_to "Ajouter +", new_produit_path, class:"form-control btn btn-primary" %>
</div>
<% content_for :title, "Produits" %>

<h1>Liste des Produits</h1>

<div id="produits">
  <% @produits.each do |produit| %>
    <div class="card">
      <div class="card-header">
        <%= render produit %>
      </div>
      <div class="card-body d-flex justify-content-around">
        <%= link_to "Modifier", edit_produit_path(produit), class:"btn btn-warning" %> 
        <%= link_to "Voir +", produit, class:"btn btn-primary" %>
      </div>
    </div>
    <p>
      
    </p>
  <% end %>
</div>

app/views/produits/new.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="row">
    <div class="col-md-12 col-md-offset-12">
      <% content_for :title, "New produit" %>

      <h1>Ajouter ouveau produit</h1>

      <%= render "form", produit: @produit %>

      <br>

      <div>
        <%= link_to "Retour", produits_path, class:"btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/produits/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="mb-3">
  <div class="card">
    <div class="card-header">
      <%= render @produit %>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-around">
        <%= link_to "Retour", produits_path, class:"btn btn-outline-primary" %>
        <%= link_to "Modification", edit_produit_path(@produit), class:"btn btn-warning" %> 
        <%= button_to "Destroy this produit", @produit, method: :delete, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
</div>