config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :ventes
  resources :produits
  resources :stocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "vente#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy!

    respond_to do |format|
      format.html { redirect_to stocks_path, status: :see_other, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.expect(stock: [ :name, :quantity, :price ])
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<div class="">
  <%= form_with(model: stock) do |form| %>
    <% if stock.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

        <ul>
          <% stock.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-md-6">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity, class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price, class:"form-control" %>
    </div>

<br/>
    <div class="form-group col-md-3">
      <%= form.submit class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Name:</strong>
    <%= stock.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= stock.quantity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= stock.price %>
  </p>

</div>

app/views/stocks/edit.html.erb
<% content_for :title, "Editing stock" %>

<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Stocks" %>

<h1>Stocks</h1>

<div id="stocks">
  <% @stocks.each do |stock| %>
    <%= render stock %>
    <p>
      <%= link_to "Show this stock", stock %>
    </p>
  <% end %>
</div>

<%= link_to "New stock", new_stock_path %>

app/views/stocks/new.html.erb
<% content_for :title, "New stock" %>

<h1>New stock</h1>

<div class="container">
  <div class="form-group ">
    <div class="row col-md-12">
      <%= render "form", stock: @stock %>
    </div>
  </div>
<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stock %>

<div>
  <%= link_to "Edit this stock", edit_stock_path(@stock) %> |
  <%= link_to "Back to stocks", stocks_path %>

  <%= button_to "Destroy this stock", @stock, method: :delete %>
</div>