config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :ventes
  resources :produits
  resources :stocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "vente#index"
end

app/models/reparation.rb
class Reparation < ApplicationRecord
    validates :name, :probleme, :price, presence: true
end

app/controllers/reparations_controller.rb
class ReparationsController < ApplicationController
  before_action :set_reparation, only: %i[ show edit update destroy ]

  # GET /reparations or /reparations.json
  def index
    @reparations = Reparation.all

    @reps = @reparations.group_by{|m| m.created_at.beginning_of_month }
    @rep_per_year = @reparations.group_by { |y| y.created_at.beginning_of_year }.transform_values { |v| v.sum(&:price) }
    
  end

  # GET /reparations/1 or /reparations/1.json
  def show
  end

  # GET /reparations/new
  def new
    @reparation = Reparation.new
  end

  # GET /reparations/1/edit
  def edit
  end

  # POST /reparations or /reparations.json
  def create
    @reparation = Reparation.new(reparation_params)

    respond_to do |format|
      if @reparation.save
        format.html { redirect_to @reparation, notice: "Reparation was successfully created." }
        format.json { render :show, status: :created, location: @reparation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reparation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reparations/1 or /reparations/1.json
  def update
    respond_to do |format|
      if @reparation.update(reparation_params)
        format.html { redirect_to @reparation, notice: "Reparation was successfully updated." }
        format.json { render :show, status: :ok, location: @reparation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reparation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reparations/1 or /reparations/1.json
  def destroy
    @reparation.destroy!

    respond_to do |format|
      format.html { redirect_to reparations_path, status: :see_other, notice: "Reparation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reparation
      @reparation = Reparation.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def reparation_params
      params.expect(reparation: [ :name, :probleme, :price ])
    end
end

app/helpers/reparations_helper.rb
module ReparationsHelper
end

app/views/reparations/_form.html.erb
<%= form_with(model: reparation) do |form| %>
  <% if reparation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reparation.errors.count, "error") %> prohibited this reparation from being saved:</h2>

      <ul>
        <% reparation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>
<br>

  <div class="form-group">
    <%= form.label :probleme, style: "display: block" %>
    <%= form.text_field :probleme, class:"form-control" %>
  </div>
<br>

  <div class="form-group">
    <%= form.label :Montant, style: "display: block" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>
<br>

  <div class="form-group ">
    <%= form.submit "Valider", class:"btn btn-primary form-control" %>
  </div>
<% end %>

app/views/reparations/_reparation.html.erb
<div id="<%= dom_id reparation %>">
  <p>
    <strong>Reparation:</strong>
    <%= reparation.name %>
  </p>

  <p>
    <strong>Probleme:</strong>
    <%= reparation.probleme %>
  </p>

  <p>
    <strong>Montant:</strong>
    <%= reparation.price %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= reparation.created_at.strftime('%B %Y') %>
  </p>

</div>

app/views/reparations/edit.html.erb
<% content_for :title, "Editing reparation" %>

<h1>Faire une modification</h1>

<%= render "form", reparation: @reparation %>

<br>

<div>
  <%= link_to "Voir", @reparation, class:"btn btn-warning" %> |
  <%= link_to "Retour", reparations_path, class:"btn btn-outline-primary" %>
</div>

app/views/reparations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Reparations" %>

<div class="form-group col-4 mx-auto ">
  <%= link_to "Ajouter +", new_reparation_path, class:"btn btn-primary " %>
</div>
<h1>Reparations</h1>
<div id="reparations">
  <% @reps.each do |month, reparations| %>
    <h2><%= month.strftime('%B %Y')  %> | Total mensuel: <%= reparations.sum(&:price)  %>F</h2>

    <% reparations.each do |reparation| %>

    <div class="mb-5">
      <div class="card">
        <div class="card-header">
          <%= render reparation %>
        </div>
        <div class="card-body d-flex justify-content-around">
          <%= link_to "Modifier", edit_reparation_path(reparation), class:"btn btn-warning" %> 
          <%= link_to "Voir +", reparation, class:"btn btn-primary" %>
        </div>
      </div>
<br>
    <% end %>
      <hr>
  <% end %>

<%
=begin%>
 
    <% @reparations.each do |reparation| %>
    <div class="card">
      <div class="card-header">
        <%= render reparation %>
      </div>
      <div class="card-body d-flex justify-content-around">
        <%= link_to "Modifier", edit_reparation_path(reparation), class:"btn btn-warning" %> 
        <%= link_to "Voir +", reparation, class:"btn btn-primary" %>
      </div>
    </div>
    <p>
      
    </p>
  <% end %> 
<%
=end%>
</div>

app/views/reparations/new.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="row">
    <div class="col-md-12 col-md-offset-12">
      <% content_for :title, "Créer une nouvelle réparation" %>

      <h1>Créer une nouvelle réparation</h1>

      <%= render "form", reparation: @reparation %>

      <br>

      <div>
        <%= link_to "Back to reparations", reparations_path %>
      </div>

    </div>
  </div>
</div>

app/views/reparations/show.html.erb
<p style="color: green"><%= notice %></p>
      <h1>Voir</h1>
<div class="mb-3">
  <div class="card">
    <div class="card-header">
      <%= render @reparation %>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-around">
        <%= link_to "Retour", reparations_path, class:"btn btn-outline-primary" %> 
        <%= link_to "Modifier", edit_reparation_path(@reparation), class:"btn btn-warning" %> 
        <%= button_to "Supprimer", @reparation, method: :delete, class:"btn btn-danger" %> 
      </div>
    </div>
  </div>
</div>