config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :ventes
  resources :produits
  resources :stocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "vente#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Commercame" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Commerçame</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item ">
          <%= link_to "Ventes", ventes_path(), class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Produits", produits_path(), class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Reparation", reparations_path(), class:"nav-link text-white" %>
        </li>
        <%
=begin%>
 <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Inventaire
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Action", class:"dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li> 
<%
=end%>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

<div class="container d-flex align-items-center justify-content-center">
  <div class="row">
    <div class="col-md-12 col-md-offset-12">
      <p class="notice" style="color: green"><%= notice %></p>
      <p class="alert" style="color: red"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
</div>
  </body>
</html>
<%
=begin%>
 

# app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

<li class="nav-item">
  <%= link_to "Home", root_path(), class: "nav-link text-white #{active_class(root_path)}" %>
</li>
<li class="nav-item">
  <%= link_to "Ventes", ventes_path, class: "nav-link text-white #{active_class(ventes_path)}" %>
</li>
<li class="nav-item">
  <%= link_to "Produits", produits_path, class: "nav-link text-white #{active_class(produits_path)}" %>
</li>

<li class="nav-item">
  <%= link_to "Inventaire", inventaire_path, class: "nav-link text-white #{active_class(inventaire_path)}" %>
</li>
 
<%
=end%>